---
- name: Install urxvt (Arch Linux)
  become: true
  community.general.pacman:
    name:
      - rxvt-unicode
      - urxvt-perls
      - ttf-dejavu
      - xsel
    state: present
    update_cache: true
