---
- name: Update pacman cache (Arch Linux)
  become: true
  community.general.pacman:
    update_cache: true
  changed_when: false

- name: Install urxvt (Arch Linux)
  become: true
  community.general.pacman:
    name:
      - rxvt-unicode
      - urxvt-perls
      - ttf-dejavu
      - xsel
    state: present
