---
- name: Install urxvt (Arch Linux)
  become: true
  community.general.pacman:
    name:
      - rxvt-unicode
      - urxvt-perls
      - ttf-dejavu
      - xsel
    state: present
    update_cache: true

- name: Enable urxvt keyboard-select plugin
  become: false
  ansible.builtin.file:
    src: /usr/lib/urxvt/perl/keyboard-select
    dest: "~/.urxvt/ext/keyboard-select"
    state: link
  tags: ['urxvt']

- name: Enable urxvt url-select plugin
  become: false
  ansible.builtin.file:
    src: /usr/lib/urxvt/perl/url-select
    dest: "~/.urxvt/ext/url-select"
    state: link
  tags: ['urxvt']
