---
- include_tasks: archlinux.yml
  when: ansible_os_family == 'Archlinux'

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: create ~/.urxvt/ext/ dir
  become: false
  file:
    path: "~/.urxvt/ext/"
    state: directory
  tags: [ 'urxvt' ]

- name: generate urxvt config files
  become: false
  template:
    src: "{{ item }}.j2"
    dest: "~/.urxvt/{{ item }}"
  with_items:
    - Xresources.dark
    - Xresources.light
    - dark.xresources
    - light.xresources
    - xresources
  tags: [ 'urxvt' ]

- name: download urxvt font-size plugin
  become: false
  get_url:
    url: https://raw.githubusercontent.com/majutsushi/urxvt-font-size/master/font-size
    dest: "~/.urxvt/ext/font-size"
  tags: [ 'urxvt' ]

  # TODO: Fix for Ubuntu
  # urxvt-perls package is not available on Ubuntu like it is Arch
  # Will have to grab the plugins directly, like font-size above
- name: enable urxvt keyboard-select plugin
  become: false
  file:
    src: /usr/lib/urxvt/perl/keyboard-select
    dest: "~/.urxvt/ext/keyboard-select"
    state: link
  when: ansible_os_family == 'Archlinux'
  tags: [ 'urxvt' ]

  # TODO: Fix for Ubuntu
  # urxvt-perls package is not available on Ubuntu like it is Arch
  # Will have to grab the plugins directly, like font-size above
- name: enable urxvt url-select plugin
  become: false
  file:
    src: /usr/lib/urxvt/perl/url-select
    dest: "~/.urxvt/ext/url-select"
    state: link
  when: ansible_os_family == 'Archlinux'
  tags: [ 'urxvt' ]
