---
- name: Uninstall urxvt (Arch Linux)
  become: true
  community.general.pacman:
    name:
      - rxvt-unicode
      - urxvt-perls
    state: absent
  when: ansible_os_family == 'Archlinux'

- name: Uninstall urxvt (Debian)
  become: true
  ansible.builtin.apt:
    name:
      - rxvt-unicode
    state: absent
  when: ansible_os_family == 'Debian'

- name: Remove ~/.urxvt directory
  become: false
  ansible.builtin.file:
    path: "~/.urxvt/"
    state: absent
  tags: ['urxvt']
